backend:
  name: git-gateway
  repo: imrzn/jekyll
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "projects"
    label: "Projects"
    folder: "_data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
